#!/usr/bin/env bash
# A script that configures the server using a redirection file
sudo apt-get update
sudo apt-get install -y nginx
String="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/H-Asmaa permanent;"
sudo sed -i "s/server_name _;/$String/" /etc/nginx/sites-enabled/default
sudo service nginx restart
