#!/usr/bin/env bash
# Display "Best School" 10 times. And if the counter is 9, display "Hi" as well

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done