#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
	# localhost resolves to 127.0.0.2
	# facebook.com resolves to 8.8.8.8.
	# The checker is running on Docker
	# before running the script, localhost resolves to 127.0.0.1 and facebook.com resolves to 157.240.11.35
	# after running the script, localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
# Explanation :
	# Step 1 : we copy the file hosts to a new file called hosts.new which is the file we will be modifying
	# Step 2 : we append the line 8.8.8.8  facebook.com to it.
	# Step 3 : instead of adding a new localhost with 127.0.0.2, we will change the existing host's IP, so
				#(that way we wont have a priority problem) Using sed.
	# Step 4 : we copy the modified file in the original file. -f meaning
sudo cp /etc/hosts ~/hosts.new
echo "127.0.0.2   localhost" > ~/hosts.new
echo "8.8.8.8    facebook.com" >>  ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
