#!/usr/bin/env bash
# A Bash script that displays all active IPv4 IPs on the machine it’s executed on.
	# ip addr show : Used to display ip addresses and network interfaces information.
	# awk '/inet / {print $2}': Filtering the line to get the ip.
	# cut -d'/' -f1 : removing the / and the number after it.
ip addr show | awk '/inet / {print $2}' | cut -d'/' -f1
